name: CI - Run Unit Tests in Docker

on:
  push:
    branches: [ main ] # Or your default branch
  # Trigger on pull requests targeting the main branch
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest # Standard runner with Docker pre-installed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image for testing
        run: |
          docker build \
            --target dev \
            --tag my-test-image:latest \
            --file Dockerfile .
        # Notes:
        # --tag my-test-image:latest : Gives the image a local name we can reference.
        # --file path/to/your/Dockerfile : IMPORTANT: Replace with the actual path to your Dockerfile.
        # . : Specifies the build context (usually the repository root).

      - name: Run tests with dFBA extra
        run: |
          docker run --rm \
            -v "$(pwd):/app" \
            -w /app \
            my-test-image:latest \
            uv run --with dfba --with pytest --with pytest-cov coverage run --source ./src -m pytest ./tests/extras --junitxml=test_report.xml

      - name: Run tests without dFBA extra
        run: |
          docker run --rm \
            -v "$(pwd):/app" \
            -w /app \
            my-test-image:latest \
            uv run --with pytest --with pytest-cov coverage run --source ./src -m pytest ./tests/core --junitxml=test_report.xml
